spring:
  application:
    name: gameBoard
  jpa:
    hibernate:
      ddl-auto: update   # ??? ?? ? DB ??? ?? ??
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect